name: build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [4.7.0, 4.6.0, 4.5.5]
        dist: ["alpine", "debian", "fedora", "ubuntu"]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
          logout: false
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: false
      - uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
          logout: false
      # - name: Build
        #run: |
        #  - echo "### Build! :rocket:" >> $GITHUB_STEP_SUMMARY
        #  - echo 'OUTPUT_BUILD<<EOF' >> $GITHUB_OUTPUT
        #  - make build CV=${{ matrix.version }} DIST=${{ matrix.dist }} >> $GITHUB_OUTPUT
        #  - echo 'EOF' >> $GITHUB_OUTPUT
      - name: Test
        run: |
          - echo "### Test! :warning:" >> $GITHUB_STEP_SUMMARY
          - echo 'OUTPUT_TEST<<EOF' >> $GITHUB_OUTPUT
          - make test CV=${{ matrix.version }} DIST=${{ matrix.dist }} >> $GITHUB_OUTPUT
          - echo 'EOF' >> $GITHUB_OUTPUT
      - name: Push
        run: |
          - echo "### Deploy! :rocket:" >> $GITHUB_STEP_SUMMARY
          - echo 'OUTPUT_DEPLOY<<EOF' >> $GITHUB_OUTPUT
          - make push CV=${{ matrix.version }} DIST=${{ matrix.dist }} >> $GITHUB_OUTPUT
          - echo 'EOF' >> $GITHUB_OUTPUT
  latest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      - name: Latest
        run: |
          - echo "### Build! :rocket:" >> $GITHUB_STEP_SUMMARY
          - echo 'OUTPUT_LATEST<<EOF' >> $GITHUB_OUTPUT
          - make latest CV=4.7.0 DIST=fedora >> $GITHUB_OUTPUT
          - echo 'EOF' >> $GITHUB_OUTPUT
